apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devjeans
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: devjeans
    server: 'https://kubernetes.default.svc'
  source:
    path: ./deployment/
    repoURL: # github repo URL
    targetRevision: main
    directory:
      recurse: true

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
